Called the NOTE variale via zeebeworker from deposit API
openMF/ph-ee-connector-ams-mifos pull request #18
Opened 2023-01-20 12:58 UTC by dhruvsonagara

## Description

1. Called the variable created in Payer API via zeebe worker which is mentioned as Description text in the GSMA/deposit API

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Design related bullet points or design document link related to this PR added in the description above. 

- [x] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [x] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-01-20 13:02 UTC, danishjamal104 approved these changes
LGTM(Looks Good To Me)

2023-01-20 13:09 UTC, fynmanoj requested changes

2023-02-03 13:47 UTC, fynmanoj commented
please rebase this PR to remove conflicts

2023-02-06 05:34 UTC, fynmanoj approved these changes

2023-02-07 05:44 UTC, fynmanoj approved these changes

2023-02-07 05:44 UTC, merged